[parity]
chain = "tendermint-chain.json"
base_path = "/tmp/parity1"
[network]
port = 30301
[rpc]
port = 8541
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[dapps]
port = 8081
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x5ffd73275a0a97ebacc63181b077a648722cd9de"
reseal_on_txs = "none"
