[parity]
chain = "tendermint-chain.json"
base_path = "/tmp/parity0"
[network]
port = 30300
[rpc]
port = 8540
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8180
[dapps]
port = 8080
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x4e47e95247a535d9c1ed9e5a73f1344a5d864383"
reseal_on_txs = "none"
